services:
  postgres:
    image: postgres:15
    container_name: betabase-db
    environment:
      POSTGRES_USER: betabase
      POSTGRES_PASSWORD: B3taBa$3
      POSTGRES_DB: betabase_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
