spring:
  profiles:
    active: dev  # Change to 'prod' or 'test' as needed

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: ${SPRING_SECURITY_USER:}
      password: ${SPRING_SECURITY_PASSWORD:}

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS}
